### ISSUE TITLE
ValidationExceptionMapper workaround

### ISSUE THREAD

**Issue by fmaitrot** [gdemecki/JERSEY-3153#1]
In hk2 (DI in Jersey) you can have multiple bindings for the same thing. By default the oldest will take precedence, but you can change this by using **rank** :

`public class ApplicationBinder extends AbstractBinder {
  @Override
  protected void configure() {
    bind(ValidationExceptionMapper.class).to(ExceptionMapper.class).in(Singleton.class).ranked(10);
  }
}`

Don't forget to register it in your JAX-RS application

**Comment by gdemecki** [comment]
Hi @fmaitrot, 
thanks, but this is just a workaround - and I've already mentioned it inside [Known workarounds](https://github.com/gdemecki/JERSEY-3153#known-workarounds) section (under "Remove Weld").

This repository exists only as a showcase for the bug related to the integration of Jersey and Weld. HK2 doesn't matter here.
